server:
  port: 8080

spring:
  application:
    name: sl-police-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: monolith_api
          uri: http://sl-police-monolith:8081
          predicates:
            - Path=/api/**
